# Generated by Django 5.1.1 on 2024-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
