# Generated by Django 5.1.1 on 2024-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_topic_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='static/uploads'),
        ),
    ]
