# Generated by Django 5.1.1 on 2024-10-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
